"""Build mdlaug_crawl/engine.bundle.js from the extension's engine sources.

The extension (../extension) is the single source of truth. The crawler ships this
generated bundle so it runs standalone. Run after changing the engine:

    python scripts/sync_engine.py          (or: npm run crawler:sync from the repo root)

tests/test_engine_bundle.py fails if the bundle is out of date with the extension.
"""
import hashlib
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
EXT = HERE.parent / "extension"
OUT = HERE / "mdlaug_crawl" / "engine.bundle.js"
FILES = ["engine/remediator.js", "packs/blacklight.js", "packs/dspace.js", "packs/islandora.js",
         "packs/omeka.js", "packs/iiif.js", "engine/assessment.js"]


def build(ext=EXT):
    parts, h = [], hashlib.sha256()
    for f in FILES:
        src = (ext / f).read_text(encoding="utf-8")
        h.update(src.encode("utf-8"))
        parts.append(f"/* ===== {f} ===== */\n{src}")
    header = ("/* GENERATED by crawler/scripts/sync_engine.py from ../extension — do not edit.\n"
              f"   source sha256: {h.hexdigest()} */\n")
    return header + "\n;\n".join(parts) + "\n"


if __name__ == "__main__":
    if not (EXT / FILES[0]).exists():
        sys.exit(f"extension sources not found at {EXT}")
    OUT.write_text(build(), encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")
