"""Per-site best-effort remediation outputs.

* draft_pack(): turns the engine's attribute fixes into a DRAFT declarative site pack
  (the extension's format: select / set / remove). Selectors come from crawled pages,
  so they are page-specific — the pack is a starting point to review and edit (e.g.
  replace a generic "Search" name with the library's own wording), not a guaranteed fix.
* site_report(): a zip with an accessible HTML report (before/after screenshots,
  every change as before → after markup, what still needs a person), plus the
  draft pack and the raw change list as JSON.
"""
import html
import json
import time
import zipfile
from pathlib import Path
from urllib.parse import urlparse

from . import analysis, scoring

DISCLAIMER = ("Best-effort, automated repair preview generated by the mDLAUG crawler. The browser extension "
              "can apply these fixes live; permanent fixes belong in the library's own templates. Every change "
              "should be reviewed, and items under 'Still needs a person' cannot be fixed automatically.")


EXTRA_LEVELS = {"FORM1": "A", "MED1": "A"}     # engine rules beyond the 24 situations


def _level_for(token):
    if token in EXTRA_LEVELS:
        return EXTRA_LEVELS[token]
    for code, lvl in scoring.SITUATIONS:
        if token in code.split("/"):
            return lvl
    return ""


def site_pages(store, run_id, site_id):
    return store.query("SELECT * FROM pages WHERE run_id=? AND site_id=? AND status='ok' ORDER BY id", (run_id, site_id))


def pack_from_pages(site, pages):
    """Draft pack from repair diffs on page rows (local SQLite or crowd/Turso rows)."""
    host = urlparse(site["collection_url"]).hostname or "site"
    rules, seen = [], set()
    for p in pages:
        d = json.loads(p.get("remediation") or "{}") if isinstance(p.get("remediation"), str) else {}
        for c in d.get("changed", []):
            sets = {x["attr"]: x["after"] for x in c["diff"]
                    if x["after"] is not None and "mdlaug" not in str(x["after"])}
            removes = [x["attr"] for x in c["diff"] if x["after"] is None]
            if not sets and not removes:
                continue
            key = (c["selector"], json.dumps(sets, sort_keys=True), tuple(removes))
            if key in seen:
                continue
            seen.add(key)
            code = (c.get("codes") or ["PACK"])[0]
            rule = {"code": code, "level": _level_for(code),
                    "describe": f"{code}: {', '.join(list(sets) + ['-' + r for r in removes])} on {p.get('page_type') or 'page'}",
                    "select": c["selector"]}
            if sets:
                rule["set"] = sets
            if removes:
                rule["remove"] = removes
            rules.append(rule)
    return {"id": f"crawl-{host}".replace(".", "-"), "title": f"{site['institution']} (draft from crawl)",
            "source": "crawl-draft",
            "note": "Generated from a crawl. Selectors are page-specific; review, generalise, and edit names before use.",
            "match": {"hosts": [host]}, "rules": rules}


def draft_pack(store, run_id, site_id):
    site = store.query("SELECT * FROM sites WHERE id=?", (site_id,))[0]
    return pack_from_pages(site, site_pages(store, run_id, site_id))


def _img(zf, path, name):
    if path and Path(path).exists():
        zf.write(path, "images/" + name)
        return "images/" + name
    return None


def site_report(store, run_id, site_id, out_zip):
    e = html.escape
    site = store.query("SELECT * FROM sites WHERE id=?", (site_id,))[0]
    pages = site_pages(store, run_id, site_id)
    t = analysis.site_situation_table(store, run_id)
    t = t[t.site_id == site_id] if not t.empty else t
    review = store.query("SELECT code, message, page_id FROM findings WHERE run_id=? AND site_id=? AND needs_review=1 "
                         "ORDER BY code", (run_id, site_id))
    pack = draft_pack(store, run_id, site_id)
    total_changed = total_added = 0
    parts = []
    with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        for p in pages:
            d = json.loads(p.get("remediation") or "{}")
            ptype = p.get("page_type") or "page"
            before = _img(zf, p.get("annotated"), f"p{p['id']}_before.png")
            after = _img(zf, p.get("after_annotated"), f"p{p['id']}_after.png")
            ch, ins = d.get("changed", []), d.get("inserted", [])
            total_changed += len(ch); total_added += len(ins)
            sec = [f'<section><h2>{e(ptype.title())} page</h2><p><a href="{e(p.get("final_url") or p["url"])}">'
                   f'{e(p.get("final_url") or p["url"])}</a></p><div class="pair">']
            if before:
                sec.append(f'<figure><img src="{before}" alt="Before repair: screenshot of the {e(ptype)} page with '
                           f'numbered marks for issues (red), items needing review (amber) and things done well (green); '
                           f'the key beside it lists each mark."><figcaption>Before — findings</figcaption></figure>')
            if after:
                sec.append(f'<figure><img src="{after}" alt="After repair: the same page with the automated fixes '
                           f'applied; changed elements are marked in teal and added elements in purple, listed in the key.">'
                           f'<figcaption>After — best-effort repair ({len(ch)} changed, {len(ins)} added)</figcaption></figure>')
            sec.append("</div>")
            if ch:
                sec.append('<h3>Changed markup</h3><table><thead><tr><th scope="col">Situation</th><th scope="col">Element '
                           '(CSS selector)</th><th scope="col">Change</th><th scope="col">Before → after</th></tr></thead><tbody>')
                for c in ch:
                    chg = "; ".join(f"{x['attr']}: {x['before'] if x['before'] is not None else '(none)'} → "
                                    f"{x['after'] if x['after'] is not None else '(removed)'}" for x in c["diff"])
                    sec.append(f"<tr><td>{e(', '.join(c.get('codes') or []))}</td><td><code>{e(c['selector'])}</code></td>"
                               f"<td>{e(chg)}</td><td><pre>{e(c['before_tag'])}\n→\n{e(c['after_tag'])}</pre></td></tr>")
                sec.append("</tbody></table>")
            if ins:
                sec.append('<h3>Added elements</h3><table><thead><tr><th scope="col">Kind</th><th scope="col">Where</th>'
                           '<th scope="col">Markup</th></tr></thead><tbody>')
                for a in ins:
                    sec.append(f"<tr><td>{e(a['kind'])}</td><td><code>{e(a['where'])}</code></td>"
                               f"<td><pre>{e(a['html'])}</pre></td></tr>")
                sec.append("</tbody></table>")
            mine = [r for r in review if r["page_id"] == p["id"]]
            if mine:
                sec.append("<h3>Still needs a person on this page</h3><ul>" +
                           "".join(f"<li><strong>{e(r['code'])}</strong> — {e(r['message'] or '')}</li>" for r in mine) + "</ul>")
            sec.append("</section>")
            parts.append("".join(sec))
        rows = "".join(f"<tr><th scope='row'>{e(r.code)}</th><td>{e(r.level)}</td>"
                       f"<td>{'' if r.score != r.score or r.score is None else int(r.score)}</td><td>{e(r.status)}</td></tr>"
                       for r in t.itertuples()) if len(t) else ""
        doc = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>mDLAUG repair report — {e(site['institution'])}</title>
<style>body{{font:15px/1.5 system-ui,sans-serif;max-width:1400px;margin:auto;padding:1rem;color:#1c2421}}
h1,h2{{color:#12332e}} .pair{{display:flex;gap:1rem;flex-wrap:wrap}} figure{{margin:0;flex:1 1 560px}}
img{{max-width:100%;border:1px solid #ccd}} table{{border-collapse:collapse;width:100%;margin:.5rem 0}}
th,td{{border:1px solid #ccd;padding:.35rem .5rem;vertical-align:top;text-align:left}} pre{{white-space:pre-wrap;margin:0;font-size:12px}}
.note{{background:#fff7e6;border-left:4px solid #d67800;padding:.6rem .8rem}}</style></head><body>
<main><h1>Repair report: {e(site['institution'])}</h1>
<p><a href="{e(site['collection_url'])}">{e(site['collection_url'])}</a> · {e(site['platform'])} · {e(site['library_type'])}
 · run {run_id} · {time.strftime('%Y-%m-%d')}</p>
<p class="note">{e(DISCLAIMER)}</p>
<p>{len(pages)} page(s) · {total_changed} element(s) changed · {total_added} element(s) added ·
 {len(pack['rules'])} draft site-pack rule(s) in <code>sitepack.json</code>.</p>
<h2>Situation scores</h2><table><thead><tr><th scope="col">Situation</th><th scope="col">Level</th>
<th scope="col">Score (1–7)</th><th scope="col">Status</th></tr></thead><tbody>{rows}</tbody></table>
{''.join(parts)}
<h2>Using the draft site pack</h2><p>In the extension: Options → Site packs → Add a pack, paste
<code>sitepack.json</code>. Review each rule first: selectors were taken from the crawled pages and names are
generic.</p></main></body></html>"""
        zf.writestr("report.html", doc)
        zf.writestr("sitepack.json", json.dumps(pack, indent=2))
        zf.writestr("changes.json", json.dumps({p["id"]: json.loads(p.get("remediation") or "{}") for p in pages}, indent=2, default=str))
    return out_zip
